language: node_js

node_js:
  - 10
  - lts/*

script:
  - yarn lint
  - yarn test
  - yarn build

cache: yarn

branches:
  only:
    - master
    - develop

notifications:
  email:
    recipients:
      - hyuuuntae@gmail.com
    on_success: change # options: [always|never|change] default: change
    on_failure: always # options: [always|never|change] default: always
